title: 我的个人博客
description: personal blog

url: http://vopjie.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: 首页
   url: /index.html
 - title: 关于我们
   url: /about
 - title: 联系我们
   url: /contact

social:
   github: vopjie
   email: jie@vopjie.com

google_analytics: "UA-58263416-1"
